### ISSUE TITLE
"Install ELK" Script

### ISSUE THREAD

**Issue by jack-michaud** [nuccdc/tools#2]
We need a script to install ELK. 

@kylesferrazza mentioned a `docker-elk` template that [I forked for the team](https://github.com/nuccdc/docker-elk). This provides a good starting point for our custom ELK stack. 

The script should
- [ ] Clone down our docker-elk repo into a specifiable location. 
- [ ] Start the services
  - [ ] Bonus: Start the services using a systemd service
- [ ] Change the passwords using the [setup passwords script](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-passwords.html) and dump the new passwords somewhere
  - [ ] Bonus: Can we encrypt the password dump?

**Comment by jack-michaud** [comment]
Can we pre-make dashboards?

**Comment by kylesferrazza** [comment]
Should also run the batch password change script that comes with elasticsearch and output the generated passwords somewhere.

**Comment by jack-michaud** [comment]
> Should also run the batch password change script that comes with elasticsearch and output the generated passwords somewhere.

@kylesferrazza Just added this to the issue description :muscle:
